#ifndef POSITION_MOCK_HPP_
#define POSITION_MOCK_HPP_

#define POSITION_MOCK_GET_X_FUNCTION "getX"
#define POSITION_MOCK_SET_X_FUNCTION "setX"
#define POSITION_MOCK_SET_X_FUNCTION_PARAMETER_X "x"
#define POSITION_MOCK_GET_Y_FUNCTION "getY"
#define POSITION_MOCK_SET_Y_FUNCTION "setY"
#define POSITION_MOCK_SET_Y_FUNCTION_PARAMETER_Y "y"

#endif // POSITION_MOCK_HPP_
