name: C/C++ CI MacOS

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: install dependencies
      run: |
        brew update
        bre install autoconf
        brew install cppunit
        brew install lcov
    - name: autoreconf
      run: autoreconf -ivf
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
