name: C/C++ CI Windows with CYGWIN

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest
    name: Windows native

    steps:
    # checkout action uses the native git (we can avoid this messing up line
    # endings, but this could still be dangerous e.g if we need symlinks in the
    # repo)
    - run: git config --global core.autocrlf input
    - uses: actions/checkout@v3

    - name: Install Cygwin
      uses: egor-tensin/setup-cygwin@v4
      with:
        packages: >-
          autoconf,
          automake,
          gcc-g++,
          make,
          cppcheck,
          libncurses-devel

    - name: Build Cygwin
      run: |
        autoreconf -ivf
        ./configure --disable-tests
        make
        make check
        make distcheck
      shell: C:\tools\cygwin\bin\bash.exe --noprofile --norc -eo pipefail -o igncr '{0}'
