name: C/C++ CI Windows with CYGWIN

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        include:
        - pkgarch: x86_64
        - pkgarch: i686
    name: Windows native ${{ matrix.pkgarch }}

    steps:
    # checkout action uses the native git (we can avoid this messing up line
    # endings, but this could still be dangerous e.g if we need symlinks in the
    # repo)
    - run: git config --global core.autocrlf input
    - uses: actions/checkout@v3

    - name: Install Cygwin
      uses: cygwin/cygwin-install-action@master
      with:
        platform: ${{ matrix.pkgarch }}
        packages: >-
          autoconf,
          automake,
          gcc-g++,
          gettext-devel,
          make,
          mingw64-${{ matrix.pkgarch }}-gcc-g++

    - name: Build Cygwin
      run: >-
        export PATH=/usr/bin:$(cygpath ${SYSTEMROOT})/system32 &&
        autoreconf -ivf &&
        ./configure &&
        make &&
        make check &&
        make distcheck
      shell: C:\cygwin\bin\bash.exe --noprofile --norc -eo pipefail '{0}'
